CC := gcc
CFLAGS := -fPIC -O3 -g -Wall -Werror
CFLAGS2 = -Wall -g -fPIC -shared
HFiles := CAENComm.h

OwnMain: OwnMain.o OwnLibrary.o
	$(CC) $(CFLAGS) OwnMain.o OwnLibrary.o -o OwnCode

OwnMain.o: OwnMain.c OwnLibrary.so
	$(CC) $(CFLAGS) -o OwnMain.c OwnLibrary.so
	
OwnLibrary.so: OwnLibrary.c $(HFiles)
	$(CC) -L $(CFLAGS2) $< -o $@ -lCAENComm
